name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  project_name: "my-project"

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            zig_target: x86_64-linux-musl
            runner: ubuntu-latest
          - goos: linux
            goarch: arm64
            zig_target: aarch64-linux-musl
            runner: ubuntu-latest
          - goos: windows
            goarch: amd64
            zig_target: x86_64-windows-gnu
            runner: ubuntu-latest
          - goos: windows
            goarch: arm64
            zig_target: aarch64-windows-gnu
            runner: ubuntu-latest
          - goos: darwin
            goarch: amd64
            runner: macos-15-intel
          - goos: darwin
            goarch: arm64
            runner: macos-latest
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Set up Zig
      if: matrix.zig_target != ''
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.15.2

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Build
      shell: bash
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 1
      run: |
        mkdir -p bin
        EXT=""
        LDFLAGS=""

        if [[ "$GOOS" == "windows" ]]; then
          EXT=".exe"
        fi
        if [[ -n "${{ matrix.zig_target }}" ]]; then
          export CC="zig cc -target ${{ matrix.zig_target }}"
          export CXX="zig c++ -target ${{ matrix.zig_target }}"

          if [[ "${{ matrix.zig_target }}" == *"musl"* ]]; then
            LDFLAGS="-linkmode external -extldflags '-static'"
          fi
        elif [[ "$GOOS" == "darwin" ]]; then
          LDFLAGS="-extldflags=-Wl,-no_warn_duplicate_libraries"
        fi

        go build \
          -trimpath \
          -buildvcs=false \
          -ldflags "-s -w -X 'main.Version=${{ github.ref_name }}' $LDFLAGS" \
          -o "bin/${{ env.project_name }}-${{ matrix.goos }}-${{ matrix.goarch }}${EXT}" .

    - name: Upload Artifact
      uses: actions/upload-artifact@v6
      with:
        name: ${{ env.project_name }}_${{ matrix.goos }}_${{ matrix.goarch }}
        path: bin/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v8
      with:
        pattern: ${{ env.project_name }}_*
        path: bin
        merge-multiple: true

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: bin/*
        name: "Release ${{ github.ref_name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}