checks = [
    "all",

	# Disable: Missing or incorrect package comment.
    "-ST1000",

	# Disable: Poorly chosen identifier (capitalization of initialisms like ID vs Id).
    "-ST1003",

	# Disable: Exported function doc must start with function name.
    "-ST1020",

	# Disable: Exported type doc must start with type name.
    "-ST1021",

	# Disable: Exported var/const doc must start with its name.
    "-ST1022",
]

http_status_code_whitelist = []
