name: Build and Deploy Site

on:
  push:
    branches:
      - master
    paths:
      - "discord/theme.css"
      - ".upgrader/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set-up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ".upgrader/go.mod"

      - name: Build Upgrader
        shell: bash
        run: |
          mkdir -p build
          [[ "${{ matrix.goos }}" == "windows" ]] && EXT=".exe" || EXT=""
          cd .upgrader
          OUT="../build/upgrader_${{ matrix.goos }}${EXT}"
          GOOS=${{ matrix.goos }} GOARCH=amd64 CGO_ENABLED=0 \
          go build -trimpath -buildvcs=false -o "$OUT" .

      - name: Upload Upgrader
        uses: actions/upload-artifact@v4
        with:
          name: upgrader_${{ matrix.goos }}
          path: build/*

  build-css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install CSS Build Dependencies
        run: npm install postcss postcss-import-url cssnano

      - name: Build CSS
        run: |
          node -e '
          const fs = require("fs"),
              postcss = require("postcss"),
              postcssImportUrl = require("postcss-import-url"),
              cssnano = require("cssnano");

          const css = fs.readFileSync("discord/theme.css", "utf8");

          postcss([
                  postcssImportUrl({
                      filter: (url) => !url.includes("fonts.googleapis.com") && !url.includes("fonts.gstatic.com")
                  }),
                  cssnano()
              ])
              .process(css, {
                  from: "discord/theme.css"
              })
              .then(result => {
                  fs.mkdirSync("css", {
                      recursive: true
                  });
                  fs.writeFileSync("css/discord.min.css", result.css);
                  console.log("CSS successfully built.");
              })
              .catch(err => {
                  console.error(err);
                  process.exit(1);
              });
          '

      - name: Upload CSS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: css-theme
          path: css/discord.min.css

  deploy:
    needs: [build-go, build-css]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: temp_artifacts

      - name: Organize Deployment Directory
        shell: bash
        run: |
          mkdir -p dist/bin dist/css

          cp temp_artifacts/css-theme/discord.min.css dist/css/

          cp temp_artifacts/upgrader_linux/upgrader_linux dist/bin/upgrader-linux
          cp temp_artifacts/upgrader_windows/upgrader_windows.exe dist/bin/upgrader-win.exe

          ls -R dist/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4